@startuml DeepLink
!theme blueprint
title Deeplink Cycle

App -> CoreMod : Process deeplink

loop subMod
    CoreMod -> CoreMod: Check submodule conform to a DeeplinkHandler protocol
    CoreMod -> SubMod: Get DeeplinkProessor
    SubMod -> SubMod: Searches for a processor\nthat matches the input
    
    alt match
        SubMod --> CoreMod: Return DeeplinkProcessor
        CoreMod -> SubMod: Executes the DeeplinkProessor

    else not match
        SubMod --> CoreMod: Return Null
    end
end
    
CoreMod --> App : Return DeeplinkResultType
App -> App : Return Handle failure cases (if need)
@enduml